#!/usr/bin/env python3
"""Generate transparent cartoon dog-local VFX sprites for ArenaFinal.

These replace white-square paw trails, action particles, and showcase polish
with couch-readable dog-specific effects while leaving movement/controller logic
unchanged.
"""

from __future__ import annotations

import math
from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path("unity/CheddarAndCocoa/Assets/Art/Resources/ArenaFinal/VFX/Dog")
REF_ROOT = Path("unity/CheddarAndCocoa/Assets/Art/ReferenceOnly/GeneratedDogFx")
SIZE = 512


def rgba(hex_value: str, alpha: int = 255) -> tuple[int, int, int, int]:
    hex_value = hex_value.lstrip("#")
    return tuple(int(hex_value[i : i + 2], 16) for i in (0, 2, 4)) + (alpha,)


def canvas() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    image = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    return image, ImageDraw.Draw(image)


def paw(draw: ImageDraw.ImageDraw, cx: int, cy: int, scale: float, fill, outline):
    r = int(42 * scale)
    draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=fill, outline=outline, width=max(4, int(8 * scale)))
    for ox, oy, tr in [(-48, -48, 18), (-16, -68, 17), (18, -68, 17), (52, -48, 18)]:
        rr = int(tr * scale)
        x = int(cx + ox * scale)
        y = int(cy + oy * scale)
        draw.ellipse((x - rr, y - rr, x + rr, y + rr), fill=fill, outline=outline, width=max(3, int(6 * scale)))


def paw_cheddar(draw: ImageDraw.ImageDraw):
    draw.ellipse((78, 344, 434, 426), fill=(0, 0, 0, 28))
    for i, (x, y, s, a) in enumerate([(166, 292, 0.86, 180), (260, 250, 1.0, 220), (356, 292, 0.86, 170)]):
        paw(draw, x, y, s, rgba("#ffbf5a", a), rgba("#6a3a12", min(255, a + 35)))
        draw.arc((x - 82, y - 92, x + 82, y + 72), 205, 330, fill=rgba("#fff07a", 150), width=9)
    draw.line((104, 354, 408, 214), fill=rgba("#ff7a28", 105), width=14)


def paw_cocoa(draw: ImageDraw.ImageDraw):
    draw.ellipse((78, 346, 434, 428), fill=(0, 0, 0, 24))
    for x, y, s, a in [(154, 296, 0.82, 160), (250, 252, 0.98, 215), (354, 286, 0.82, 160)]:
        paw(draw, x, y, s, rgba("#63f1e6", a), rgba("#165b62", min(255, a + 45)))
        draw.arc((x - 88, y - 88, x + 88, y + 78), 205, 330, fill=rgba("#c8fff6", 145), width=8)
    draw.line((112, 344, 402, 222), fill=rgba("#45aaff", 95), width=12)


def chaos_spark(draw: ImageDraw.ImageDraw):
    points = []
    for i in range(16):
        angle = -math.pi / 2 + i * math.pi * 2 / 16
        radius = 178 if i % 2 == 0 else 70
        points.append((256 + math.cos(angle) * radius, 256 + math.sin(angle) * radius))
    draw.polygon(points, fill=rgba("#ff7a28", 230), outline=rgba("#5c230c"))
    points2 = []
    for i in range(12):
        angle = -math.pi / 2 + i * math.pi * 2 / 12 + 0.2
        radius = 118 if i % 2 == 0 else 42
        points2.append((256 + math.cos(angle) * radius, 256 + math.sin(angle) * radius))
    draw.polygon(points2, fill=rgba("#fff070", 235), outline=rgba("#8b4a10"))
    draw.ellipse((224, 224, 288, 288), fill=rgba("#ffffff", 220))


def queen_glint(draw: ImageDraw.ImageDraw):
    draw.ellipse((108, 236, 404, 276), fill=rgba("#5df6ee", 85))
    draw.polygon([(256, 54), (292, 214), (458, 256), (292, 298), (256, 458), (220, 298), (54, 256), (220, 214)],
                 fill=rgba("#86fff4", 205), outline=rgba("#155b63"))
    draw.polygon([(256, 128), (280, 226), (384, 256), (280, 286), (256, 384), (232, 286), (128, 256), (232, 226)],
                 fill=rgba("#ffffff", 210), outline=rgba("#58cdd9"))


def ground_glow(draw: ImageDraw.ImageDraw):
    for i, box in enumerate([(56, 166, 456, 346), (100, 194, 412, 318), (154, 220, 358, 294)]):
        draw.ellipse(box, fill=rgba("#fff2a4", [62, 72, 92][i]), outline=rgba("#6debe4", [54, 48, 40][i]), width=6)
    draw.arc((94, 172, 418, 340), 195, 345, fill=rgba("#ffffff", 110), width=10)


def collar_glint(draw: ImageDraw.ImageDraw):
    draw.rounded_rectangle((86, 224, 426, 286), radius=26, fill=rgba("#ffef72", 180), outline=rgba("#593611"), width=9)
    draw.polygon([(256, 118), (284, 224), (402, 256), (284, 288), (256, 394), (228, 288), (110, 256), (228, 224)],
                 fill=rgba("#ffffff", 225), outline=rgba("#ffca3a"))
    draw.ellipse((218, 218, 294, 294), fill=rgba("#77fff4", 155), outline=rgba("#155b63"), width=6)


DRAWERS = {
    "dog_fx_chaos_spark": chaos_spark,
    "dog_fx_collar_glint": collar_glint,
    "dog_fx_ground_glow": ground_glow,
    "dog_fx_paw_cheddar": paw_cheddar,
    "dog_fx_paw_cocoa": paw_cocoa,
    "dog_fx_queen_glint": queen_glint,
}


def write_readme():
    REF_ROOT.mkdir(parents=True, exist_ok=True)
    names = "\n".join(f"- `{name}.png`" for name in sorted(DRAWERS))
    (REF_ROOT / "README.md").write_text(
        "# Generated Dog FX Pack\n\n"
        "Deterministic transparent dog-local VFX generated by "
        "`tools/art/generate_dog_fx_pack.py`. Runtime code uses these for paw trails, action "
        "particles, collar glints, and dog-local showcase polish while preserving the existing "
        "movement and feedback timing. These are couch-test VFX assets, not a final hand-authored "
        "animation/effects pipeline.\n\n"
        f"{names}\n",
        encoding="utf-8",
    )


def write_contact_sheet(images: list[tuple[str, Image.Image]]):
    REF_ROOT.mkdir(parents=True, exist_ok=True)
    cell = 256
    sheet = Image.new("RGBA", (cell * 3, cell * 2), (245, 240, 226, 255))
    for i, (name, image) in enumerate(images):
        thumb = image.resize((cell, cell), Image.Resampling.LANCZOS)
        sheet.alpha_composite(thumb, ((i % 3) * cell, (i // 3) * cell))
    sheet.convert("RGB").save(REF_ROOT / "dog_fx_pack_contact_sheet.png", quality=95)


def main():
    ROOT.mkdir(parents=True, exist_ok=True)
    generated: list[tuple[str, Image.Image]] = []
    for name, draw_fn in DRAWERS.items():
        image, draw = canvas()
        draw_fn(draw)
        image.save(ROOT / f"{name}.png")
        generated.append((name, image))
    write_readme()
    write_contact_sheet(generated)
    print(f"Generated {len(generated)} dog FX sprites in {ROOT}")


if __name__ == "__main__":
    main()
