#!/usr/bin/env python3
"""Generate the role-turn beacon cue sprite for ArenaFinal (G1.3).

One neutral cream paw badge with a soft glow ring, tinted at runtime via
SpriteRenderer.color to the owning dog's identity color (Cheddar orange /
Cocoa brown) - same runtime-tint approach RoleTurnBeacon's neighbor,
ObjectiveArrowFeedback's scent breadcrumbs, already uses on cue_target_paw.
A separate baked-per-dog-color sprite isn't needed because of that.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path("unity/CheddarAndCocoa/Assets/Art/Resources/ArenaFinal/UI/Cues")
REF_ROOT = Path("unity/CheddarAndCocoa/Assets/Art/ReferenceOnly/GeneratedRoleBeaconCue")
SIZE = 512


def rgba(hex_value: str, alpha: int = 255) -> tuple[int, int, int, int]:
    hex_value = hex_value.lstrip("#")
    return tuple(int(hex_value[i : i + 2], 16) for i in (0, 2, 4)) + (alpha,)


def canvas() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    image = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    return image, ImageDraw.Draw(image)


def paw(draw: ImageDraw.ImageDraw, cx: int, cy: int, scale: float, fill, outline):
    r = int(34 * scale)
    draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=fill, outline=outline, width=max(3, int(7 * scale)))
    for ox, oy, tr in [(-38, -42, 16), (-12, -58, 15), (16, -58, 15), (42, -42, 16)]:
        rr = int(tr * scale)
        x = int(cx + ox * scale)
        y = int(cy + oy * scale)
        draw.ellipse((x - rr, y - rr, x + rr, y + rr), fill=fill, outline=outline, width=max(2, int(5 * scale)))


def role_beacon(draw: ImageDraw.ImageDraw):
    # Soft glow rings behind the paw so it reads as an active beacon, not a static prop icon.
    for radius, alpha, width in [(226, 60, 22), (182, 90, 16), (140, 120, 10)]:
        draw.ellipse((256 - radius, 256 - radius, 256 + radius, 256 + radius),
                     outline=rgba("#ffffff", alpha), width=width)
    paw(draw, 256, 260, 1.55, rgba("#f5f0e0"), rgba("#3a2a18"))
    draw.arc((100, 92, 412, 404), 205, 335, fill=rgba("#ffffff", 150), width=14)


DRAWERS = {
    "cue_role_beacon": role_beacon,
}


def write_readme():
    REF_ROOT.mkdir(parents=True, exist_ok=True)
    (REF_ROOT / "README.md").write_text(
        "# Generated Role-Turn Beacon Cue\n\n"
        "Deterministic transparent cartoon paw badge generated by "
        "`tools/art/generate_role_beacon_cue.py`. RoleTurnBeacon tints this neutral cream sprite "
        "to the owning dog's identity color at runtime (Cheddar orange / Cocoa brown) rather than "
        "baking two color variants, matching how the existing scent-breadcrumb paw cue is tinted.\n\n"
        "- `cue_role_beacon.png`\n",
        encoding="utf-8",
    )


def write_contact_sheet(images: list[tuple[str, Image.Image]]):
    REF_ROOT.mkdir(parents=True, exist_ok=True)
    cell = 256
    sheet = Image.new("RGBA", (cell * max(1, len(images)), cell), (245, 240, 226, 255))
    for i, (name, image) in enumerate(images):
        thumb = image.resize((cell, cell), Image.Resampling.LANCZOS)
        sheet.alpha_composite(thumb, (i * cell, 0))
    sheet.convert("RGB").save(REF_ROOT / "role_beacon_cue_contact_sheet.png", quality=95)


def main():
    ROOT.mkdir(parents=True, exist_ok=True)
    generated: list[tuple[str, Image.Image]] = []
    for name, draw_fn in DRAWERS.items():
        image, draw = canvas()
        draw_fn(draw)
        image.save(ROOT / f"{name}.png")
        generated.append((name, image))
    write_readme()
    write_contact_sheet(generated)
    print(f"Generated {len(generated)} role-beacon cue sprite(s) in {ROOT}")


if __name__ == "__main__":
    main()
