#!/usr/bin/env python3
"""Generate transparent world-label skin sprites for ArenaFinal.

These sprites replace raw floating TextMesh-only presentation for mission
object labels and score pops while keeping the existing label strings,
positions, and controller-owned gameplay state authoritative.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path("unity/CheddarAndCocoa/Assets/Art/Resources/ArenaFinal/UI/WorldLabels")
REF_ROOT = Path("unity/CheddarAndCocoa/Assets/Art/ReferenceOnly/GeneratedWorldLabelSkin")
SIZE = 512


def rgba(hex_value: str, alpha: int = 255) -> tuple[int, int, int, int]:
    hex_value = hex_value.lstrip("#")
    return tuple(int(hex_value[i : i + 2], 16) for i in (0, 2, 4)) + (alpha,)


def canvas() -> tuple[Image.Image, ImageDraw.ImageDraw]:
    image = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    return image, ImageDraw.Draw(image)


def paw(draw: ImageDraw.ImageDraw, cx: int, cy: int, s: float, fill):
    r = int(13 * s)
    draw.ellipse((cx - r, cy - r, cx + r, cy + r), fill=fill)
    for ox, oy, tr in [(-16, -17, 6), (-5, -24, 5), (7, -24, 5), (18, -17, 6)]:
        rr = int(tr * s)
        x = int(cx + ox * s)
        y = int(cy + oy * s)
        draw.ellipse((x - rr, y - rr, x + rr, y + rr), fill=fill)


def world_label_bubble(draw: ImageDraw.ImageDraw):
    draw.rounded_rectangle((52, 138, 460, 352), radius=54, fill=(0, 0, 0, 74))
    draw.rounded_rectangle((42, 112, 470, 326), radius=48, fill=rgba("#17333a", 230),
                           outline=rgba("#f8df78"), width=12)
    draw.rounded_rectangle((70, 142, 442, 296), radius=36, outline=rgba("#7bd9df", 130), width=6)
    draw.polygon([(224, 318), (288, 318), (256, 382)], fill=rgba("#17333a", 230),
                 outline=rgba("#f8df78"))
    draw.arc((66, 126, 446, 306), 196, 332, fill=rgba("#ffffff", 46), width=8)
    paw(draw, 92, 168, 0.72, rgba("#f8df78", 165))
    paw(draw, 422, 274, 0.58, rgba("#ff785f", 150))


def world_label_command(draw: ImageDraw.ImageDraw):
    draw.rounded_rectangle((42, 156, 470, 340), radius=40, fill=(0, 0, 0, 68))
    draw.rounded_rectangle((58, 134, 454, 310), radius=36, fill=rgba("#f2b84f", 236),
                           outline=rgba("#5b3518"), width=12)
    draw.rounded_rectangle((94, 166, 418, 278), radius=28, fill=rgba("#fff1aa", 125),
                           outline=rgba("#ffffff", 72), width=5)
    draw.polygon([(42, 222), (82, 178), (82, 266)], fill=rgba("#17333a", 225),
                 outline=rgba("#f8df78"))
    draw.polygon([(470, 222), (430, 178), (430, 266)], fill=rgba("#17333a", 225),
                 outline=rgba("#f8df78"))
    paw(draw, 132, 222, 0.78, rgba("#17333a", 190))
    draw.line((184, 222, 366, 222), fill=rgba("#17333a", 95), width=14)


def world_label_warning(draw: ImageDraw.ImageDraw):
    draw.rounded_rectangle((54, 152, 458, 344), radius=38, fill=(0, 0, 0, 80))
    draw.polygon([(256, 84), (476, 366), (36, 366)], fill=rgba("#ff6f58", 232),
                 outline=rgba("#552017"))
    draw.polygon([(256, 122), (424, 336), (88, 336)], fill=rgba("#ffe37e", 226),
                 outline=rgba("#ffffff"))
    draw.rectangle((238, 176, 274, 268), fill=rgba("#552017", 230))
    draw.ellipse((238, 286, 274, 322), fill=rgba("#552017", 230))
    paw(draw, 118, 330, 0.62, rgba("#552017", 165))
    paw(draw, 394, 330, 0.62, rgba("#552017", 165))


def world_pop_burst(draw: ImageDraw.ImageDraw):
    points = []
    for i in range(24):
        import math

        angle = math.radians(i * 15)
        radius = 214 if i % 2 == 0 else 156
        points.append((256 + int(math.cos(angle) * radius), 256 + int(math.sin(angle) * radius)))
    draw.polygon(points, fill=(0, 0, 0, 62))
    points = []
    for i in range(24):
        import math

        angle = math.radians(i * 15)
        radius = 196 if i % 2 == 0 else 136
        points.append((256 + int(math.cos(angle) * radius), 244 + int(math.sin(angle) * radius)))
    draw.polygon(points, fill=rgba("#fff17a", 234), outline=rgba("#6a3a18"))
    draw.ellipse((122, 116, 390, 372), fill=rgba("#ffbf54", 220), outline=rgba("#ffffff", 160), width=7)
    paw(draw, 256, 250, 2.0, rgba("#17333a", 200))


DRAWERS = {
    "world_label_bubble": world_label_bubble,
    "world_label_command": world_label_command,
    "world_label_warning": world_label_warning,
    "world_pop_burst": world_pop_burst,
}


def write_readme():
    REF_ROOT.mkdir(parents=True, exist_ok=True)
    names = "\n".join(f"- `{name}.png`" for name in sorted(DRAWERS))
    (REF_ROOT / "README.md").write_text(
        "# Generated World Label Skin Pack\n\n"
        "Deterministic transparent cartoon skins generated by "
        "`tools/art/generate_world_label_skin_pack.py`. Runtime TextMesh strings, positions, and "
        "mission-controller state remain authoritative, but mission labels and score pops draw these "
        "sprites behind the text instead of reading as raw floating placeholder text.\n\n"
        f"{names}\n",
        encoding="utf-8",
    )


def write_contact_sheet(images: list[tuple[str, Image.Image]]):
    REF_ROOT.mkdir(parents=True, exist_ok=True)
    cell = 192
    cols = 4
    sheet = Image.new("RGBA", (cell * cols, cell), (246, 240, 228, 255))
    for i, (_name, image) in enumerate(images):
        thumb = image.resize((cell, cell), Image.Resampling.LANCZOS)
        sheet.alpha_composite(thumb, (i * cell, 0))
    sheet.convert("RGB").save(REF_ROOT / "world_label_skin_pack_contact_sheet.png", quality=95)


def main():
    ROOT.mkdir(parents=True, exist_ok=True)
    generated: list[tuple[str, Image.Image]] = []
    for name, draw_fn in DRAWERS.items():
        image, draw = canvas()
        draw_fn(draw)
        image.save(ROOT / f"{name}.png")
        generated.append((name, image))
    write_readme()
    write_contact_sheet(generated)
    print(f"Generated {len(generated)} world-label skin sprites in {ROOT}")


if __name__ == "__main__":
    main()
